#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://github.com/Minecrell/ServerListPlus/releases/download/3.4.7/ServerListPlus-3.4.7-Server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/ServerListPlus.yml ]
then
    curl "http://www.carm.ml/host/uploads/ServerListPlus.yml" -o /data/ServerListPlus.yml
fi

cd /data/; java -jar minecraft_server.jar
